import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic

namespace MeasureTheory

/-- For a sub-sigma-algebra `m`, `μ[f | m]` is the conditional expectation of `f` with respect to
`m`. For a measurable function `g`, `μ[f | g]` is the conditional expectation of `f` with respect to
the sub-sigma-algebra generated by `g`. -/
notation μ "[" f "|" cond "]" => MeasureTheory.condExp m μ f
